version: 2
before:
  hooks:
    - make dep
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm: ["6", "7"]
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.Commit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
    main: ./cmd/keepalived-exporter
nfpms:
  - id: keepalived-exporter
    package_name: keepalived-exporter
    homepage: https://github.com/mehdy/keepalived-exporter
    maintainer: Mehdi Khoshnoodi <mehdy.khoshnoody@gmail.com>
    description: Prometheus exporter for keepalived
    license: GPL-3.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
kos:
  - repositories:
      - ghcr.io/mehdy/keepalived-exporter
      - mehdy/keepalived-exporter
    tags:
      - latest
      - "{{ .Tag }}"
    platforms:
      - linux/arm/v6
      - linux/arm/v7
      - linux/arm64
      - linux/amd64
      - linux/386
    base_image: alpine
    bare: true
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: github-native
